### PR TITLE
Some supervisor rework

### PR DESCRIPTION
**Pull request by lucabrunox**
- Add supervisord.package
- Add supervisord.stateDir
- Set pidfile, logdir and childlogdir in the config,
  to make it easier from command line to override
  the single values
- Create a wrapper for supervisord and supervisorctl
- Only pass flags to supervisord if STATEDIR is non-empty
- Allow passing custom flags to supervisord and supervisorctl
- Add passthru.config to the resulting env
- Use stdenv.shell, because /bin/sh shebang is not patched

The config.supervisord.bin is very useful in nix dev environments,
where you can just run supervisord to start all services and
supervisorctl to manage the services.

Also setting a config.supervisord.stateDir allows to run
supervisord from any directory in nix-shell. Useful if you
have multiple clones of your repository, and still want to
share the services state.

### CODE REVIEW

**Comment by offlinehacker** [comment]
Well i have a slightly different use case. I build services with hydra, and don't require nix-shell, so i would really like to keep projectName-start-services, without this installation of multiple services is not possible.

**Comment by lucabrunox** [comment]
The returned buildEnv is still `${name}-services`.

**Comment by lucabrunox** [comment]
Thoughts? :)

**Comment by offlinehacker** [comment]
Ah yes, i missed something in my last review, i'm merging this.

**Pull request merged**
